name: project02_hackloop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.3
  connectivity_plus: ^3.0.2
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  ntp: ^2.0.0
  flutter_native_splash: ^2.3.10
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/

flutter_native_splash:
  color: "#BB1009"
  color_dark: "#340000"
  image: assets\logo\meals_large.png
  image_dark: assets\logo\meals_large.png
  
  android_12:
    color: "#BB1009"
    color_dark: "#340000"
    image: C:\Programming\Flutter\meals\assets\logo\meals_large.png
    image_dark: C:\Programming\Flutter\meals\assets\logo\meals_large.png
  web: false